name = "soucriala"
compatibility_date = "2026-08-13"
pages_build_output_dir = "dist"

[assets]
not_found_handling = "single-page-application"

[vars]
VITE_SUPABASE_URL = "https://mppxkcbhbhjdoctggkhk.supabase.co"
VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wcHhrY2JoYmhqZG9jdGdna2hrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY0NzYwNzYsImV4cCI6MjEwMjA1MjA3Nn0.ATrXDNqOa68DJ5UFaYr04TDoQNyZzTydPk1eCGdSA6M"
